[package]
name = "target-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "IDR Target Agent service binary"
repository.workspace = true

[[bin]]
name = "target-agent"
path = "src/main.rs"

[features]
default = []
webrtc = ["idr-target/webrtc"]

[dependencies]
idr-target = { workspace = true }
idr-dp = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
prometheus = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
